/camera_node:
  ros__parameters:
    image_save_path: '/home/zqh/robot1/robot1_ws/src/fishbot_rgbd/images_rgbd'
    initial_point:
    - 0.0
    - 0.0
    - 0.0
    target_points:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 1.0
    - 1.57
    use_sim_time: false
